apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Dispatch multiple workflows
on:
  push:
    branches:
      - 'workflow-dispatch'

jobs:
  dispatch-workflows:
    steps:
      - name: checkout-source-code
        uses: cloudbees-io/checkout@v1
  
      - name: Dispatch workflows
        uses: cloudbees-io/workflows-dispatch@main
        # uses: ./
        with:
          workflows-dispatch-file: dispatch_request.json
          token: "cb_api_dqRJZVVH59NdV4iRvcNW90gxotdEWvkHd2iNUaADxtswax9EatKWzw8sKx1agfAT0ei1iVug5ihum7Vy3ocgPQ=="
          wait-for-completion: false

